name: Build and Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build executable
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            bun run build:win
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:mac
            else
              bun run build:mac-arm
            fi
          else  # Linux
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:linux
            else
              bun run build:linux-arm
            fi
          fi
        shell: bash

      - name: Prepare package (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir package
          Copy-Item -Path '.cache' -Destination 'package\.cache' -Recurse
          Copy-Item -Path 'drizzle' -Destination 'package\drizzle' -Recurse
          Copy-Item -Path 'public' -Destination 'package\public' -Recurse
          Copy-Item -Path '.puppeteerrc.cjs' -Destination 'package\.puppeteerrc.cjs'
          Copy-Item -Path 'bin\sidewinder.exe' -Destination 'package\sidewinder.exe'
        shell: pwsh

      - name: Prepare package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir package
          cp -r drizzle public .cache .puppeteerrc.cjs bin/sidewinder package/
        shell: bash

      - name: Compress Package (Windows)
        if: runner.os == 'Windows'
        run: |
          $VERSION = '${{ github.event.release.tag_name }}'
          Compress-Archive -Path 'package/*' -DestinationPath "sidewinder-$VERSION-windows-${{ matrix.arch }}.zip"
        shell: pwsh

      - name: Compress Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          tar -czvf sidewinder-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C package .
        shell: bash

      - name: Upload Release Asset (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sidewinder-${{ github.event.release.tag_name }}-windows-${{ matrix.arch }}.zip
          asset_name: sidewinder-${{ github.event.release.tag_name }}-windows-${{ matrix.arch }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Linux/macOS)
        if: runner.os != 'Windows'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sidewinder-${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_name: sidewinder-${{ github.event.release.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
