name: Build and Package

on:
  push:
    tags:
      - "v*" # Runs only on version tags like v1.0, v1.0.0, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64] # Supports both x64 and ARM64 architectures

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build executable
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:win
            fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:mac
            else
              bun run build:mac-arm
            fi
          else  # Linux
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:linux
            else
              bun run build:linux-arm
            fi
          fi

      - name: Prepare package
        run: |
          mkdir package
          cp -r drizzle public bin/sidewinder package/

      - name: Compress Package
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            Compress-Archive -Path package/* -DestinationPath sidewinder-${VERSION}-windows-${{ matrix.arch }}.zip
          else
            tar -czvf sidewinder-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C package .
        shell: pwsh

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: sidewinder-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            sidewinder-${{ github.ref_name }}-windows-${{ matrix.arch }}.zip
            sidewinder-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
