name: Build and Package

on:
  push:
    tags:
      - "v*" # Runs only on version tags like v1.0, v1.0.0, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64] # Supports both x64 and ARM64 architectures
      exclude:
        - os: windows-latest
          arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build executable
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            bun run build:win
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:mac
            else
              bun run build:mac-arm
            fi
          else  # Linux
            if [[ "${{ matrix.arch }}" == "x64" ]]; then
              bun run build:linux
            else
              bun run build:linux-arm
            fi
          fi
        shell: bash

      - name: Prepare package (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir package
          Copy-Item -Path 'drizzle' -Destination 'package\drizzle' -Recurse
          Copy-Item -Path 'public' -Destination 'package\public' -Recurse
          mkdir package\bin
          Copy-Item -Path 'bin\sidewinder.exe' -Destination 'package\bin\sidewinder.exe'
        shell: pwsh

      - name: Prepare package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir package
          cp -r drizzle public bin/sidewinder package/
        shell: bash

      - name: Compress Package (Windows)
        if: runner.os == 'Windows'
        run: |
          $VERSION = $env:GITHUB_REF -replace 'refs/tags/', ''
          Compress-Archive -Path 'package/*' -DestinationPath "sidewinder-$VERSION-windows-${{ matrix.arch }}.zip"
        shell: pwsh

      - name: Compress Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          tar -czvf sidewinder-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C package .
        shell: bash

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            sidewinder-${{ github.ref_name }}-windows-${{ matrix.arch }}.zip
            sidewinder-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          tag: ${{ github.ref_name }}
          allowUpdates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
